### ISSUE TITLE
Add create itinerary function

### ISSUE THREAD

**Issue by wataru-maeda** [WataruMaeda/tourism-app#7]
# Description

Add function to create the itinerary

# UX

1. User tap a cell item or maker in the map
2. Present custom popover. The popover contains `spot name`, `description`, `place type` and `create itinerary button` (Need to consider the items)

# Todo

- [ ] Consider presenting items
- [ ]  Add custom popover
- [ ] Add navigation to move edit itinerary screen
